context:
  name: helloworld
  version: 0.1.0

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  number: 0

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ccache
